version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 3.0.0
  - dependency-name: grunt-contrib-nodeunit
    versions:
    - 2.1.0
  - dependency-name: grunt-replace
    versions:
    - 1.0.1
